server:
  port: 9090

spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 8e625b27-6716-48f3-a281-9ddeffd4d96c
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: http://localhost:8080
      eager: true
      datasource:
        flow-rule:
          nacos:
            server-addr: localhost:8848
            data-id: nacos-provider-flow-rules
            groupId: DEFAULT_GROUP
            rule-type: flow
            namespace: 8e625b27-6716-48f3-a281-9ddeffd4d96c
        param-flow-rule:
          nacos:
            server-addr: localhost:8848
            data-id: nacos-provider-flow-rules
            groupId: DEFAULT_GROUP
            rule-type: param_flow
            namespace: 8e625b27-6716-48f3-a281-9ddeffd4d96c
  application:
    name: nacos-provider

